drivers: touchscreen: nvt: Properly arrange variables to disable firmware update
* This is needed because Init_BootLoader and Resume_PD is needed
  regardless in nt36xxx_ext_proc while the whole fw_update file
  is ifdef'd with BOOT_UPDATE_FIRMWARE
* Fixes this error when building with BOOT_UPDATE_FIRMWARE disabled:

drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.o: In function `nvt_get_oem_data':
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:630: undefined reference to `Resume_PD'
drivers/input/touchscreen/nvt_touch_d2s/nt36xxx_ext_proc.c:624: undefined reference to `Init_BootLoader'

Signed-off-by: sohamxda7 <sensoham135@gmail.com>
Signed-off-by: Oktapra Amtono <oktapra.amtono@gmail.com>
Signed-off-by: clarencelol <clarencekuiek@icloud.com>
Signed-off-by: pix106 <sbordenave@gmail.com>